function [plObj,isHold] = prepareminkoperation(getEllArr,fCalcBodyTriArr,fCalcCenterTriArr,varargin)
import elltool.plot.plotgeombodyarr;
    [reg,~,isShowAll]=...
        modgen.common.parseparext(varargin,...
        {'showAll' ;...
        false;
        @(x)isa(x,'logical')});
    [plObj,nDim,isHold]= plotgeombodyarr('ellipsoid',fCalcBodyTriArr,@patch,reg{:});
    if (nDim < 3)
        [reg]=...
            modgen.common.parseparext(reg,...
            {'relDataPlotter';...
            [],;@(x)isa(x,'smartdb.disp.RelationDataPlotter'),...
            });
        plObj= plotgeombodyarr('ellipsoid',fCalcCenterTriArr,...
            @(varargin)patch(varargin{:},'marker','*'),reg{:},'relDataPlotter',plObj, 'priorHold',true,'postHold',isHold);
    end
    if isShowAll
        [reg]=...
            modgen.common.parseparext(reg,...
            {'relDataPlotter','newFigure','fill','lineWidth','color','shade','priorHold','postHold'});
        ellArr = cellfun(@(x)getEllArr(x),reg,'UniformOutput', false);
        ellArr = vertcat(ellArr{:});
        plObj = ellArr.plot('color', [0 0 0],'relDataPlotter',plObj);
    end
end