classdef ContinuousReachRegrTestCase < ...
        elltool.reach.test.mlunit.AReachRegrTestCase
    methods
        function self = ContinuousReachRegrTestCase(varargin)
            self = self@elltool.reach.test.mlunit.AReachRegrTestCase(...
                elltool.linsys.LinSysContinuousFactory(), ...
                elltool.reach.ReachContinuousFactory(), ...
                varargin{:});
        end
    end
end