classdef ContinuousReachRegrAdvTestCase < ...
        elltool.reach.test.mlunit.AReachRegrAdvTestCase
    methods
        function self = ContinuousReachRegrAdvTestCase(varargin)
            self = self@elltool.reach.test.mlunit.AReachRegrAdvTestCase(...
                elltool.linsys.LinSysContinuousFactory(), ...
                elltool.reach.ReachContinuousFactory(), ...
                varargin{:});
        end
    end
end