classdef DiscreteReachRegrTestCase < ...
        elltool.reach.test.mlunit.AReachRegrTestCase
    methods
        function self = DiscreteReachRegrTestCase(varargin)
            self = self@elltool.reach.test.mlunit.AReachRegrTestCase(...
                elltool.linsys.LinSysDiscreteFactory, ...
                elltool.reach.ReachDiscreteFactory, ...
                varargin{:});
        end
    end
end