function updateetalons()
dirName=[fileparts(which(mfilename('fullpath'))),filesep,...
    '+mlunit',filesep,'TestData',filesep,'SuiteRegression',...
    filesep,'testRegression_out'];
gras.ellapx.smartdb.util.updateondiskrels(dirName);