function results=run_tests(varargin)
% resList{1}=modgen.containers.test.run_tests();
% resList{2}=modgen.configuration.test.run_tests();
% resList{3}=modgen.xml.test.run_tests;
resList{4}=modgen.common.test.run_tests();
% resList{5}=modgen.probability.test.run_tests;
% resList{6}=modgen.struct.test.run_tests;
% resList{7}=modgen.date.test.run_tests;
resList{8}=modgen.string.test.run_tests;
% resList{9}=modgen.interp.test.run_tests;
% resList{10}=modgen.logging.test.run_tests;
% resList{11}=modgen.logging.log4j.test.run_tests(varargin{:});
% resList{12}=modgen.cell.test.run_tests;
% resList{13}=modgen.kernelreg.test.run_tests;
% resList{14}=modgen.profiling.test.run_tests;
resList{15}=modgen.pcalc.test.run_tests(varargin{:});
% resList{16}=modgen.metricengine.test.run_tests;
% resList{17}=modgen.microsoft.test.run_tests;
results=[resList{:}];
