curLoc=fileparts(mfilename('fullpath'));
testFileName=[curLoc,filesep,'test_file.txt'];
obj=modgen.logging.EmailLogger(...
    'emailDistributionList',{'bill@microsoft.com'},...
    'emailAttachmentNameList',{testFileName},...
    'smtpServer','smtp.microsoft.com',...
    'subjectSuffix','for somethings',...
    'loggerName','someApp');
obj.sendMessage('calculation started','calculation started');
obj.sendMessage('calculation started');