function SInput=patch_003_modify_log4j_settings(~,SInput)
if(~isfield(SInput, 'logging'))
    SInput.logging = struct;
end
%
TAB_PREFIX='\n\t\t\t';
logConfLineList={...
			'log4j.rootLogger=INFO, stdout',...
			'log4j.logger.elltool.reach = INFO, A1',...
			'log4j.additivity.elltool.reach = true',...
			'log4j.logger.gras.ellapx = DEBUG, A1',...
			'log4j.additivity.gras.ellapx = true',...
			'log4j.appender.stdout=org.apache.log4j.ConsoleAppender',...
			'log4j.appender.stdout.layout=org.apache.log4j.PatternLayout',...
			'log4j.appender.stdout.layout.ConversionPattern=%5p %c - %m\n',...
			'log4j.appender.A1=org.apache.log4j.DailyRollingFileAppender',...
			'#do not change - name of the main log file should have a',...
			'#fixed pattern so that email logger can pick it up',...
			'log4j.appender.A1.File=${elltool.log4j.logfile.dirwithsep}${elltool.log4j.logfile.main.name}',...
			'log4j.appender.A1.layout=org.apache.log4j.PatternLayout',...
			'log4j.appender.A1.layout.ConversionPattern=%d %5p %c - %m%n',...
			'#',...
			'log4j.appender.A2=org.apache.log4j.DailyRollingFileAppender',...
			'#',...
			'log4j.appender.A2.File=${elltool.log4j.logfile.dirwithsep}reachcont.constrcallcount.${elltool.log4j.curProcessName}.${elltool.log4j.logfile.ext}',...
			'#',...
			'log4j.appender.A2.layout=org.apache.log4j.PatternLayout',...
			'log4j.appender.A2.layout.ConversionPattern=%d %5p %c - %m%n',...
			'#',...
			'log4j.additivity.elltool.ReachCont.constrCallCount=false',...
			'#',...
			'log4j.logger.elltool.ReachCont.constrCallCount=DEBUG,A2',...
            };
logConfLineList=cellfun(@(x)sprintf([TAB_PREFIX,'%s'],x),logConfLineList,...
    'UniformOutput',false);
SInput.logging.log4jSettings=[logConfLineList{:},sprintf(TAB_PREFIX)];