classdef AEllTubeProj < ...
        gras.ellapx.smartdb.rels.AEllTubeNotTightProj & ...
        gras.ellapx.smartdb.rels.IEllTubeProj
    %
    methods (Access=protected)
        function checkTouchCurves(self,fullRel)
            import gras.ellapx.enums.EProjType;
            %
            TIGHT_PROJ_TOL=1e-15;
            %
            self.checkTouchCurveVsQNormArray(fullRel,fullRel,...
                @(x)max(x-1),...
                ['any touch line''s projection should be within ',...
                'its tube projection'],@(x,y)x==y);
            isTightDynamicVec=...
                (fullRel.lsGoodDirNorm>=1-TIGHT_PROJ_TOL)&...
                (fullRel.projType==EProjType.DynamicAlongGoodCurve);
            rel=fullRel.getTuples(isTightDynamicVec);
            self.checkTouchCurveVsQNormArray(rel,rel,...
                @(x)abs(x-1),...
                ['for dynamic tight projections touch line should be ',...
                'on the boundary of tube''s projection'],...
                @(x,y)x==y);
        end
    end
    %
    methods (Access=protected)
        function checkDataConsistency(self)
            checkDataConsistency@...
                gras.ellapx.smartdb.rels.AEllTubeNotTightProj(self);
        end
        function fieldList=getPlotArgumentsFieldList(self)
            import gras.ellapx.smartdb.F
            %
            FIELDS={'X_TOUCH_CURVE_MAT','X_TOUCH_OP_CURVE_MAT'};
            %
            fieldList=getPlotArgumentsFieldList@...
                gras.ellapx.smartdb.rels.AEllTubeNotTightProj(self);
            %
            fieldList=[fieldList,F.getNameList(FIELDS)];
        end
        %
        function hVec=plotCreateTubeTouchCurveFunc(self,hAxes,~,...
                timeVec,lsGoodDirOrigVec,~,sTime,...
                ltGoodDirNormVec,ltGoodDirNormOrigVec,xTouchCurveMat,...
                xTouchOpCurveMat)
            %
            [cMat,cOpMat]=self.getGoodCurveColor(ltGoodDirNormVec,...
                ltGoodDirNormOrigVec);
            hVec(2)=dispTouchCurve(xTouchCurveMat,lsGoodDirOrigVec,cMat);
            hVec(1)=dispTouchCurve(xTouchOpCurveMat,-lsGoodDirOrigVec,cOpMat);
            %
            function hVec=dispTouchCurve(xTouchCurveMat,lsGoodDirOrigVec,cMat)
                import modgen.graphics.plot3adv;
                %
                plotName=['Good curve: ',...
                    self.goodDirProp2Str(lsGoodDirOrigVec,sTime)];
                propList={'lineWidth',2,...
                    'Parent',hAxes,'DisplayName',plotName};
                hVec=plot3adv(timeVec.',xTouchCurveMat(1,:).',...
                    xTouchCurveMat(2,:).',cMat,propList{:});
            end
        end
        %
        function hVec=plotCreateReachTubeFunc(self,fGetPatchColor,...
                hAxes,projType,timeVec,lsGoodDirOrigVec,ltGoodDirMat,...
                sTime,ltGoodDirNormVec,ltGoodDirNormOrigVec,approxType,...
                QArray,aMat,MArray,varargin)
            %
            import gras.ellapx.enums.EApproxType;
            %
            hVec=plotCreateReachTubeFunc@...
                gras.ellapx.smartdb.rels.AEllTubeNotTightProj(...
                self,fGetPatchColor,hAxes,projType,timeVec,...
                lsGoodDirOrigVec,ltGoodDirMat,sTime,ltGoodDirNormVec,...
                ltGoodDirNormOrigVec,approxType,QArray,aMat,MArray,...
                varargin{:});
            %
            if approxType==EApproxType.External
                hTouchVec=self.plotCreateTubeTouchCurveFunc(...
                    hAxes,projType,timeVec,lsGoodDirOrigVec,ltGoodDirMat,...
                    sTime,ltGoodDirNormVec,ltGoodDirNormOrigVec,...
                    varargin{:});
                hVec=[hVec,hTouchVec];
            end
        end
    end
end