classdef ObjectApproxControlParams
    properties (Constant=true)
        nAddTopElems=32;
        errorCheckMode=1.e-3;
        approxPrec=1;
        freeMemoryMode=0;
        discardIneqMode=1;
        incDim=0;
        faceDist=.9e-5;
        inApproxDist=1.e-4;
        ApproxDist=1.e-5;
        precTest=1.e-4;
        relPrec=1.e-5;
        inftyDef=1.e6;
        isVerbose=0;
    end
    methods
        
        function propVal=getPropValue(self,propName)
            propVal=getfield(self,propName);  %#ok<GFLD>
        end
        
        function defaultValVec=getValues(self,propList)
            defaultValVec=zeros(1,numel(propList));
            for iElem=1:numel(propList)
                defaultValVec(iElem)= self.getPropValue(propList{iElem});
            end
        end
        function SParams=convexHullParams(self,paramsSetList)
            import modgen.common.checkmultvar;
            propList={'nAddTopElems','errorCheckMode','approxPrec',...
                'freeMemoryMode','discardIneqMode','incDim','faceDist',...
                'inApproxDist','ApproxDist','precTest','relPrec',...
                'inftyDef','isVerbose'};
            defaultValVec=self.getValues(propList);
            [~,~,...
                SParams.nAddTopElems,SParams.errorCheckMode,SParams.approxPrec,...
                SParams.freeMemoryMode,SParams.discardIneqMode,...
                SParams.incDim,SParams.faceDist,SParams.inApproxDist,...
                SParams.ApproxDist,SParams.precTest,SParams.relPrec,...
                SParams.inftyDef, SParams.isVerbose]=...
                modgen.common.parseparext(paramsSetList,...
                {'nAddTopElems','errorCheckMode','approxPrec',...
                'freeMemoryMode','discardIneqMode','incDim','faceDist',...
                'inApproxDist','ApproxDist','precTest','relPrec',...
                'inftyDef','isVerbose';...
                defaultValVec(1),defaultValVec(2),defaultValVec(3),...
                defaultValVec(4),defaultValVec(5),defaultValVec(6),...
                defaultValVec(7),defaultValVec(8),defaultValVec(9),...
                defaultValVec(10),defaultValVec(11),defaultValVec(12)...
                defaultValVec(13);});
            
            checkmultvar('(x1<x2)&&(x1<x3)',3,SParams.faceDist,...
                SParams.ApproxDist,SParams.precTest, 'errorTag',...
                'wrongParams','errorMessage',...
                'faceDist must be less then ApproxDist and precTest');
            
        end
        function SParams=ellipsoidApproxParams(self,paramsSetList)
            import modgen.common.checkmultvar;
            propList={'approxPrec','freeMemoryMode',...
                'discardIneqMode','faceDist','inApproxDist','ApproxDist',...
                'relPrec','inftyDef','isVerbose'};
            defaultValVec=self.getValues(propList);
            [~,~,...
                SParams.approxPrec,SParams.freeMemoryMode,SParams.discardIneqMode,...
                SParams.faceDist,SParams.inApproxDist,SParams.ApproxDist,...
                SParams.relPrec,SParams.inftyDef,SParams.isVerbose]=...
                modgen.common.parseparext(paramsSetList,...
                {'approxPrec','freeMemoryMode',...
                'discardIneqMode','faceDist','inApproxDist','ApproxDist',...
                'relPrec','inftyDef','isVerbose';...
                defaultValVec(1),defaultValVec(2),defaultValVec(3),...
                defaultValVec(4),defaultValVec(5),defaultValVec(6),...
                defaultValVec(7),defaultValVec(8),defaultValVec(9);});
            SParams.nAddTopElems=self.getPropValue('nAddTopElems');
            SParams.errorCheckMode=self.getPropValue('errorCheckMode');
            SParams.incDim=self.getPropValue('incDim');
            SParams.precTest=self.getPropValue('precTest');
            
            checkmultvar('(x1<x2)',2,SParams.faceDist,SParams.ApproxDist,...
                'errorTag','wrongParams','errorMessage',...
                'faceDist must be less then ApproxDist');
            
        end
    end
end