classdef ObjectApproxControlParams
    properties (Constant=true)
        nAddTopElems=32;
        errorCheckMode=1.e-3;
        approxPrec=1;
        freeMemoryMode=0;
        discardIneqMode=1;
        incDim=0;
        faceDist=.9e-5;
        inApproxDist=1.e-4;
        ApproxDist=1.e-5;
        precTest=1.e-4;
        relPrec=1.e-5;
        inftyDef=1.e6;
        isVerbose=0;
    end
    methods
        
        function propVal=getPropValue(self,propName) %#ok<MANU>
            propVal=elltool.multobj.ObjectApproxControlParams.(propName);
        end
        
        function defaultValVec=getValues(self,propList)
            defaultValVec=zeros(1,numel(propList));
            for iElem=1:numel(propList)
                defaultValVec(iElem)= self.getPropValue(propList{iElem});
            end
        end
        function SParams=parseParams(self,paramsSetList,propList)
            import modgen.common.checkmultvar;
            defaultValVec=self.getValues(propList);
            [~,~,...
                SParams.(propList{1}),SParams.(propList{2}),...
                SParams.(propList{3}),SParams.(propList{4}),...
                SParams.(propList{5}),SParams.(propList{6}),...
                SParams.(propList{7}),SParams.(propList{8}),...
                SParams.(propList{9}),SParams.(propList{10}),...
                SParams.(propList{11}),...
                SParams.(propList{12}), SParams.(propList{13})]=...
                modgen.common.parseparext(paramsSetList,...
                {propList{1:numel(propList)};...
                defaultValVec(1),defaultValVec(2),defaultValVec(3),...
                defaultValVec(4),defaultValVec(5),defaultValVec(6),...
                defaultValVec(7),defaultValVec(8),defaultValVec(9),...
                defaultValVec(10),defaultValVec(11),defaultValVec(12)...
                defaultValVec(13);});
            
            checkmultvar('(x1<x2)&&(x1<x3)',3,SParams.(propList{7}),...
                SParams.(propList{9}),SParams.(propList{10}), 'errorTag',...
                'wrongParams','errorMessage',...
                'faceDist must be less then ApproxDist and precTest');
            
        end
        
    end
end