curfolder=pwd;
dest=fileparts(which('+elltool\+multobj\s_build.m'));
path=modgen.path.rmlastnpathparts(dest,2);
 path =[path filesep 'multobj' filesep 'source' filesep 'code_files'];
 cd(path)
 mex -outdir '..\..\..\+elltool\+multobj' mexconvexhull.c GRS_Points.c...
     CH_0DAT.c CH_INIT.c CH_MEM.c CH_PRIMA.c CH_TXT.c CH_DAT.c CH_CALC.c ...
     CH_EQU.c CH_EST.c CH_PRN.c CH_READP.c CH_SCOMB.c
 mex -outdir '..\..\..\+elltool\+multobj' mexellipsoidapprox.c GRS.c ...
     CH_0DAT.c CH_INIT.c CH_MEM.c CH_PRIMA.c CH_TXT.c CH_DAT.c CH_CALC.c ...
     CH_EQU.c CH_EST.c CH_PRN.c CH_READP.c CH_SCOMB.c
 cd(curfolder)