
 t = 0.886;
 ctObj = rsObj.cut(t);
 bctObj = brsObj.cut(t);
 efEllMat = ctObj.get_ea();
 ebEllMat = bctObj.get_ea();
 gc1 = ctObj.get_goodcurves(); 
 gc1 = gc1{1};
%  dst = ebEllMat.distance(gc1);
%  id = find(dst == max(dst));
 gc2 = bct.get_goodcurves(); 
%  gc2 = gc2{id};
 gc2 = gc2{1};
 fc = ctObj.get_center();
 bc = bctObj.get_center();
 gc2 = -(gc2 - bc) + bc;
 ctObj.plotByEa(); hold on;
 bctObj.plotByEa('g'); hold on;
 ell_plot(gc1,'r*');
 ell_plot(gc2,'k*');
