res=mfilename;
dirName=fileparts(mfilename('fullpath'));
SRes=load([dirName,filesep,'vaMetricTSObj.mat']);
smartdb.disp.plotts(SRes.vaMetricTSObj,'xfieldname', 'time_stamp_ts',...
                'yfieldname','metric_value_ts',...
                'figuregroupby','inst_id', 'figurenameby','inst_name',...
                'axesgroupby','vametric_configured_id','axesnameby',...
                'vametric_configured_name',...
                'graphnameby','vametric_configured_name','linkAxes','x');