function isOk=iscellnumeric(value)
if iscell(value)
    if isempty(value)
        isOk=false;
    else
        isOk=all(reshape(cellfun('isclass',value,'double'),[],1))||...
            all(reshape(cellfun('isclass',value,'int32'),[],1))||...
            all(reshape(cellfun('isclass',value,'int64'),[],1))||...
            all(reshape(cellfun('isclass',value,'int16'),[],1))||...
            all(reshape(cellfun('isclass',value,'int8'),[],1))||...
            all(reshape(cellfun('isclass',value,'uint32'),[],1))||...
            all(reshape(cellfun('isclass',value,'uint64'),[],1))||...
            all(reshape(cellfun('isclass',value,'uint16'),[],1))||...
            all(reshape(cellfun('isclass',value,'uint8'),[],1))||...
            all(reshape(cellfun('isclass',value,'single'),[],1));
    end
else
    isOk=false;
end