function results=run_tests(varargin)
results = gras.ellapx.lreachplain.probdef.test.run_tests_for_package(...
    'gras.ellapx.lreachplain.probdef',...
    'gras.ellapx.lreachplain.probdef.test.mlunit.ProbDefPlainTC',...
    varargin{:});