classdef EllipsoidDispStructTC < elltool.core.test.mlunit.ADispStructTC
    %
    %$Author: Alexander Karev <Alexander.Karev.30@gmail.com> $
    %$Date: 2013-06$
    %$Copyright: Moscow State University,
    %            Faculty of Computational Mathematics
    %            and Computer Science,
    %            System Analysis Department 2013 $
    methods (Access = protected, Static)
        function objArrCVec = getToStructObj()
            objArrCVec = {ellipsoid([1, 1]', eye(2)),...
                ellipsoid(),...
                ellipsoid([1, 1]', eye(2)),...
                ellipsoid([1, 1]', eye(2)),...
                ellipsoid([1, 1]', eye(2)),...
                ellipsoid.fromRepMat(1, 1, [5 5 5]),...
                ellipsoid.fromRepMat(1, 1, [5 5 5])};
            objArrCVec{7}(1) = ellipsoid();
        end
        
        function SArrCVec = getToStructStruct()
            SArrCVec = {struct('shapeMat', eye(2), 'centerVec', [1, 1]'),...
                struct('shapeMat', [], 'centerVec', []),...
                struct('shapeMat', [], 'centerVec', []),...
                struct('shapeMat', eye(2), 'centerVec', [1, 1]',...
                'absTol', 1e-7, 'relTol', 1e-5,...
                'nPlot2dPoints', 200, 'nPlot3dPoints', 200),...
                struct('shapeMat', eye(2), 'centerVec', [2, 1]'),...
                struct('shapeMat', num2cell(ones(5, 5, 5)), ...
                'centerVec', num2cell(ones(5, 5, 5))),...
                struct('shapeMat', num2cell(ones(5, 5, 5)), ...
                'centerVec', num2cell(ones(5, 5, 5)))};
        end
        
        function isPropCVec = getToStructIsPropIncluded()
            isPropCVec = {false, false, false, true, false, false, false};
        end
        
        function isResultCVec = getToStructResult()
            isResultCVec = {true, true, false, true, false, true, false};
        end
        
        function testNumber = getToStructTestNumber()
            testNumber = 7;
        end
        
        function objArrCVec = getFromStructObj()
            objArrCVec = {ellipsoid([1, 1]', eye(2)),...
                ellipsoid([1, 1]', eye(2), 'absTol', 1e-8,...
                'relTol', 1e-4, 'nPlot2dPoints', 300, ...
                'nPlot3dPoints', 100),...
                ellipsoid(),...
                ellipsoid([1, 1]', eye(2)),...
                ellipsoid.fromRepMat(1, 1, [5 5 5]),...
                ellipsoid.fromRepMat(1, 1, [5 5 5])};
            objArrCVec{6}(1) = ellipsoid();
        end
        
        function SArrCVec = getFromStructStruct()
            SArrCVec = {struct('shapeMat', eye(2), 'centerVec', [1, 1]),...
                struct('shapeMat', eye(2), 'centerVec', [1, 1],...
                'absTol', 1e-8, 'relTol', 1e-4,...
                'nPlot2dPoints', 300, 'nPlot3dPoints', 100),...
                struct('shapeMat', eye(2), 'centerVec', [1, 1],...
                'absTol', 1e-8, 'relTol', 1e-4,...
                'nPlot2dPoints', 300, 'nPlot3dPoints', 100),...
                struct('shapeMat', eye(2), 'centerVec', [1, 1],...
                'absTol', 1e-8, 'relTol', 1e-4,...
                'nPlot2dPoints', 300, 'nPlot3dPoints', 100),...
                struct('shapeMat', num2cell(ones(5, 5, 5)),...
                'centerVec', num2cell(ones(5, 5, 5))),...
                struct('shapeMat', num2cell(ones(5, 5, 5)),...
                'centerVec', num2cell(ones(5, 5, 5)))};
        end
        
        function isResultCVec = getFromStructResult()
            isResultCVec = {true, true, false, false, true, false};
        end
        
        function testNumber = getFromStructTestNumber()
            testNumber = 6;
        end
        
        function objArrCVec = getDisplayObj()
            objArrCVec = {ellipsoid([1, 1]', eye(2)),...
                ellipsoid(),...
                ellipsoid([1, 2]', eye(2)),...
                ellipsoid.fromStruct(struct('shapeMat',...
                num2cell(ones(5, 5, 5)), ...
                'centerVec', num2cell(ones(5, 5, 5)))),...
                ellipsoid.fromStruct(struct('shapeMat', ...
                num2cell(ones(5, 5, 5)), ...
                'centerVec', num2cell(ones(5, 5, 5)))),...
                hyperplane()};
            objArrCVec{5} = [objArrCVec{5} objArrCVec{5}];
        end
        
        function stringsCVec = getDisplayStrings()
            stringsCVec = {'Ellipsoid shape matrix.', ...
                'ellipsoid object',...
                'centerVec',...
                'shapeMat'};
            stringsCVec = repmat({stringsCVec}, 1, 6);
            stringsCVec{5} = horzcat(stringsCVec{5}, 'ObjArr(1, 1, 1)');
        end
        
        function isResultCVec = getDisplayResult()
            isResultCVec = {true, true, true, true, true, false};
        end
        
        function testNumber = getDisplayTestNumber()
            testNumber = 6;
        end
        
        function objArrCVec = getEqFstObj()
            objArrCVec = {ellipsoid([1, 1]', eye(2)),...
                ellipsoid(),...
                ellipsoid([1, 2]', eye(2)),...
                ellipsoid(),...
                ellipsoid(),...
                ellipsoid.fromStruct(struct('shapeMat',...
                num2cell(ones(5, 5, 5)), ...
                'centerVec', num2cell(ones(5, 5, 5)))),...
                ellipsoid.fromStruct(struct('shapeMat',...
                num2cell(ones(5, 5, 5)), ...
                'centerVec', num2cell(ones(5, 5, 5)))),...
                ellipsoid.fromRepMat([1, 1]', eye(2), [1 2])};
        end
        
        function objArrCVec = getEqSndObj()
            objArrCVec = {ellipsoid([1, 1]', eye(2)),...
                ellipsoid(),...
                ellipsoid([1, 2]', eye(2)),...
                ellipsoid([1, 2]', eye(2)),...
                ellipsoid([1, 1]', eye(2)),...
                ellipsoid.fromStruct(struct('shapeMat',...
                num2cell(ones(5, 5, 5)), ...
                'centerVec', num2cell(ones(5, 5, 5)))),...
                ellipsoid.fromStruct(struct('shapeMat',...
                num2cell(ones(5, 5, 5)), ...
                'centerVec', num2cell(ones(5, 5, 5)))),...
                ellipsoid.fromRepMat([1, 1]', eye(2), [1 2])};
            objArrCVec{7}(1, 1, 1) = ellipsoid();
        end
        
        function isResultCVec = getEqResult()
            isResultCVec = {true, true, true, false,...
                false, true, false, true};
        end
        
        function testNumber = getEqTestNumber()
            testNumber = 8;
        end
    end
    
    methods (Access = public)
        function self = EllipsoidDispStructTC(varargin)
            self = self@elltool.core.test.mlunit.ADispStructTC(varargin{:});
        end
    end
end