classdef EllipsoidDispStructTC < elltool.core.test.mlunit.ADispStructTC
    %
    %$Author: Alexander Karev <Alexander.Karev.30@gmail.com> $
    %$Date: 2013-06$
    %$Copyright: Moscow State University,
    %            Faculty of Computational Mathematics
    %            and Computer Science,
    %            System Analysis Department 2013 $
    methods (Static)
        function ellObj = ellipsoid(varargin)
            ellObj = ...
                elltool.core.test.mlunit.TEllipsoidFactory.createInstance(...
                'ellipsoid', varargin{:});            
        end
        function hpObj = hyperplane(varargin)
            hpObj = ...
                elltool.core.test.mlunit.TEllipsoidFactory.createInstance(...
                'hyperplane', varargin{:});            
        end
    end
    %
    methods (Access = protected, Static)
        function objArrCVec = getToStructObj()
            import elltool.core.test.mlunit.EllipsoidDispStructTC;
            objArrCVec = {EllipsoidDispStructTC.ellipsoid([1, 1]', eye(2)),...
                EllipsoidDispStructTC.ellipsoid(),...
                EllipsoidDispStructTC.ellipsoid([1, 1]', eye(2)),...
                EllipsoidDispStructTC.ellipsoid([1, 1]', eye(2)),...
                EllipsoidDispStructTC.ellipsoid([1, 1]', eye(2)),...
                EllipsoidDispStructTC.ellipsoid.fromRepMat(1, 1, [5 5 5]),...
                EllipsoidDispStructTC.ellipsoid.fromRepMat(1, 1, [5 5 5])};
            objArrCVec{7}(1) = EllipsoidDispStructTC.ellipsoid();
        end
        
        function SArrCVec = getToStructStruct()
            import elltool.conf.Properties;
            SArrCVec = {struct('shapeMat', eye(2), 'centerVec', [1, 1]'),...
                struct('shapeMat', [], 'centerVec', []),...
                struct('shapeMat', [], 'centerVec', []),...
                struct('shapeMat', eye(2), 'centerVec', [1, 1]',...
                'absTol', Properties.getAbsTol, 'relTol',Properties.getRelTol,...
                'nPlot2dPoints', Properties.getNPlot2dPoints,...
                'nPlot3dPoints', Properties.getNPlot3dPoints),...
                struct('shapeMat', eye(2), 'centerVec', [2, 1]'),...
                struct('shapeMat', num2cell(ones(5, 5, 5)), ...
                'centerVec', num2cell(ones(5, 5, 5))),...
                struct('shapeMat', num2cell(ones(5, 5, 5)), ...
                'centerVec', num2cell(ones(5, 5, 5)))};
        end
        
        function isPropCVec = getToStructIsPropIncluded()
            isPropCVec = {false, false, false, true, false, false, false};
        end
        
        function isResultCVec = getToStructResult()
            isResultCVec = {true, true, false, true, false, true, false};
        end
        
        function testNumber = getToStructTestNumber()
            testNumber = 7;
        end
        
        function objArrCVec = getFromStructObj()
            import elltool.core.test.mlunit.EllipsoidDispStructTC;
            objArrCVec = {EllipsoidDispStructTC.ellipsoid([1, 1]', eye(2)),...
                elltool.core.test.mlunit.EllipsoidDispStructTC.ellipsoid([1, 1]', eye(2), 'absTol', 1e-8,...
                'relTol', 1e-4, 'nPlot2dPoints', 300, ...
                'nPlot3dPoints', 100),...
                EllipsoidDispStructTC.ellipsoid(),...
                EllipsoidDispStructTC.ellipsoid([1, 1]', eye(2)),...
                EllipsoidDispStructTC.ellipsoid.fromRepMat(1, 1, [5 5 5]),...
                EllipsoidDispStructTC.ellipsoid.fromRepMat(1, 1, [5 5 5])};
            objArrCVec{6}(1) = EllipsoidDispStructTC.ellipsoid();
        end
        
        function SArrCVec = getFromStructStruct()
            SArrCVec = {struct('shapeMat', eye(2), 'centerVec', [1, 1]),...
                struct('shapeMat', eye(2), 'centerVec', [1, 1],...
                'absTol', 1e-8, 'relTol', 1e-4,...
                'nPlot2dPoints', 300, 'nPlot3dPoints', 100),...
                struct('shapeMat', eye(2), 'centerVec', [1, 1],...
                'absTol', 1e-8, 'relTol', 1e-4,...
                'nPlot2dPoints', 300, 'nPlot3dPoints', 100),...
                struct('shapeMat', eye(2), 'centerVec', [1, 1],...
                'absTol', 1e-8, 'relTol', 1e-4,...
                'nPlot2dPoints', 300, 'nPlot3dPoints', 100),...
                struct('shapeMat', num2cell(ones(5, 5, 5)),...
                'centerVec', num2cell(ones(5, 5, 5))),...
                struct('shapeMat', num2cell(ones(5, 5, 5)),...
                'centerVec', num2cell(ones(5, 5, 5)))};
        end
        
        function isResultCVec = getFromStructResult()
            isResultCVec = {true, true, false, false, true, false};
        end
        
        function testNumber = getFromStructTestNumber()
            testNumber = 6;
        end
        
        function objArrCVec = getDisplayObj()
            import elltool.core.test.mlunit.EllipsoidDispStructTC;
            objArrCVec = {EllipsoidDispStructTC.ellipsoid([1, 1]', eye(2)),...
                EllipsoidDispStructTC.ellipsoid(),...
                EllipsoidDispStructTC.ellipsoid([1, 2]', eye(2)),...
                EllipsoidDispStructTC.ellipsoid.fromStruct(struct('shapeMat',...
                num2cell(ones(5, 5, 5)), ...
                'centerVec', num2cell(ones(5, 5, 5)))),...
                EllipsoidDispStructTC.ellipsoid.fromStruct(struct('shapeMat', ...
                num2cell(ones(5, 5, 5)), ...
                'centerVec', num2cell(ones(5, 5, 5)))),...
                EllipsoidDispStructTC.hyperplane()};
            objArrCVec{5} = [objArrCVec{5} objArrCVec{5}];
        end
        
        function stringsCVec = getDisplayStrings()
            stringsCVec = {'Ellipsoid shape matrix.', ...
                'ellipsoid object',...
                'centerVec',...
                'shapeMat'};
            stringsCVec = repmat({stringsCVec}, 1, 6);
            stringsCVec{5} = horzcat(stringsCVec{5}, 'objArr(1, 1, 1)');
        end
        
        function isResultCVec = getDisplayResult()
            isResultCVec = {true, true, true, true, true, false};
        end
        
        function testNumber = getDisplayTestNumber()
            testNumber = 6;
        end
        
        function objArrCVec = getEqFstObj()
            import elltool.core.test.mlunit.EllipsoidDispStructTC;
            objArrCVec = {EllipsoidDispStructTC.ellipsoid([1, 1]', eye(2)),...
                EllipsoidDispStructTC.ellipsoid(),...
                EllipsoidDispStructTC.ellipsoid([1, 2]', eye(2)),...
                EllipsoidDispStructTC.ellipsoid(),...
                EllipsoidDispStructTC.ellipsoid(),...
                EllipsoidDispStructTC.ellipsoid.fromStruct(struct('shapeMat',...
                num2cell(ones(5, 5, 5)), ...
                'centerVec', num2cell(ones(5, 5, 5)))),...
                EllipsoidDispStructTC.ellipsoid.fromStruct(struct('shapeMat',...
                num2cell(ones(5, 5, 5)), ...
                'centerVec', num2cell(ones(5, 5, 5)))),...
                EllipsoidDispStructTC.ellipsoid.fromRepMat([1, 1]', eye(2), [1 2])};
        end
        
        function objArrCVec = getEqSndObj()
            import elltool.core.test.mlunit.EllipsoidDispStructTC;
            objArrCVec = {elltool.core.test.mlunit.EllipsoidDispStructTC.ellipsoid([1, 1]', eye(2)),...
                EllipsoidDispStructTC.ellipsoid(),...
                EllipsoidDispStructTC.ellipsoid([1, 2]', eye(2)),...
                EllipsoidDispStructTC.ellipsoid([1, 2]', eye(2)),...
                EllipsoidDispStructTC.ellipsoid([1, 1]', eye(2)),...
                EllipsoidDispStructTC.ellipsoid.fromStruct(struct('shapeMat',...
                num2cell(ones(5, 5, 5)), ...
                'centerVec', num2cell(ones(5, 5, 5)))),...
                EllipsoidDispStructTC.ellipsoid.fromStruct(struct('shapeMat',...
                num2cell(ones(5, 5, 5)), ...
                'centerVec', num2cell(ones(5, 5, 5)))),...
                EllipsoidDispStructTC.ellipsoid.fromRepMat([1, 1]', eye(2), [1 2])};
            objArrCVec{7}(1, 1, 1) = EllipsoidDispStructTC.ellipsoid();
        end
        
        function isResultCVec = getEqResult()
            isResultCVec = {true, true, true, false,...
                false, true, false, true};
        end
        
        function testNumber = getEqTestNumber()
            testNumber = 8;
        end
    end
    
    methods (Access = public)
        function self = EllipsoidDispStructTC(varargin)
            self = self@elltool.core.test.mlunit.ADispStructTC(varargin{:});
        end
    end
end