classdef EllipsoidDispStructTC < elltool.core.test.mlunit.ADispStruct
    %
    %$Author: Alexander Karev <Alexander.Karev.30@gmail.com> $
    %$Date: 2013-06$
    %$Copyright: Moscow State University,
    %            Faculty of Computational Mathematics
    %            and Computer Science,
    %            System Analysis Department 2013 $ 
    methods
        function self = EllipsoidDispStructTC(varargin)
            self = self@elltool.core.test.mlunit.ADispStruct(varargin{:});
        end
        
        function self = testToStruct(self)
            ell = ellipsoid([1, 1]', eye(2));
            ellStruct = struct('shapeMat', eye(2), 'centerVec', [1, 1]);
            toStructTest(self, ell, ellStruct, false, true);
            
            ellStruct = struct('shapeMat', eye(2), 'centerVec', [1, 1],...
                               'absTol', 1e-7, 'relTol', 1e-5,...
                               'nPlot2dPoints', 200, 'nPlot3dPoints', 200);
            toStructTest(self, ell, ellStruct, true, true);              
            
            ellStruct = struct('shapeMat', eye(2), 'centerVec', [2, 1]);
            toStructTest(self, ell, ellStruct, false, false);
        end
        
        function self = testFromStruct(self)
            ell = ellipsoid([1, 1]', eye(2));
            ellStruct = struct('shapeMat', eye(2), 'centerVec', [1, 1]);
            fromStructTest(self, ellStruct, ell, ellipsoid(), true);
            
            ellStruct = struct('shapeMat', eye(2), 'centerVec', [1, 1],...
                               'absTol', 1e-8, 'relTol', 1e-4,...
                               'nPlot2dPoints', 300, 'nPlot3dPoints', 100);
            ell = ellipsoid([1, 1]', eye(2), 'absTol', 1e-8,...
                               'relTol', 1e-4, 'nPlot2dPoints', 300, ...
                               'nPlot3dPoints', 100);
            fromStructTest(self, ellStruct, ell, ellipsoid(), true);              
            
            ell = ellipsoid([1, 2]', eye(2));
            fromStructTest(self, ellStruct, ell, ellipsoid(), false);  
        end
        
        function self = testDisplay(self)
            ell = ellipsoid([1, 1]', eye(2));
            str = sprintf( ['\n-------ellipsoid object-------\n',...
                            'Properties:\n',...
                            '   |\n',...
                            '   |-- actualClass : ''ellipsoid''\n',...
                            '   |--------- size : [1 1]\n',...
                            '\n',...
                            'Fields (name, type, description):\n',...
                            '    Q    double    Ellipsoid shape matrix.\n',...
                            '    a    double    Ellipsoid center vector.\n',...
                            '\n',...
                            'Data: \n',...
                            '   |    \n',...
                            '   |-- centerVec : [1 1]\n',...
                            '   |               -----\n',...
                            '   |--- shapeMat : |1|0|\n',...
                            '   |               |0|1|\n',...
                            '   |               -----\n']);
            displayTest(self, ell, str, true);
            
            ell = ellipsoid([1, 2]', eye(2));
            displayTest(self, ell, str, false);
            
            ell = [ell, ell];
            str = sprintf( ['\n-------ellipsoid object-------\n',...
                            'Properties:\n',...
                            '   |\n',...
                            '   |-- actualClass : ''ellipsoid''\n',...
                            '   |--------- size : [1 2]\n',...
                            '\n',...
                            'Fields (name, type, description):\n',...
                            '    Q    double    Ellipsoid shape matrix.\n',...
                            '    a    double    Ellipsoid center vector.\n',...
                            '\n',...
                            'Data: \n',...
                            ' \n',...
                            'ObjArr(1)\n',...
                            '   |    \n',...
                            '   |-- centerVec : [1 2]\n',...
                            '   |               -----\n',...
                            '   |--- shapeMat : |1|0|\n',...
                            '   |               |0|1|\n',...
                            '   |               -----\n',...
                            '   O\n',...
                            ' \n',...
                            'ObjArr(2)\n',...
                            '   |    \n',...
                            '   |-- centerVec : [1 2]\n',...
                            '   |               -----\n',...
                            '   |--- shapeMat : |1|0|\n',...
                            '   |               |0|1|\n',...
                            '   |               -----\n',...
                            '   O\n']);
            displayTest(self, ell, str, true);
        end
    end
end