classdef HyperplaneDispStructTC < elltool.core.test.mlunit.ADispStructTC
    %
    %$Author: Alexander Karev <Alexander.Karev.30@gmail.com> $
    %$Date: 2013-06$
    %$Copyright: Moscow State University,
    %            Faculty of Computational Mathematics
    %            and Computer Science,
    %            System Analysis Department 2013 $
    methods (Access = protected, Static)
        
        function objArrCVec = getToStructObj()
            import elltool.core.test.mlunit.TEllipsoidFactory;
            hpObj = TEllipsoidFactory.createInstance('hyperplane');
            objArrCVec = {elltool.core.test.mlunit.TEllipsoidFactory.createInstance('hyperplane', [1, 1, 2]', 3),...
                TEllipsoidFactory.createInstance('hyperplane'),...
                TEllipsoidFactory.createInstance('hyperplane', [1, 1, 2]', 3),...
                TEllipsoidFactory.createInstance('hyperplane', [1, 1, 2]', 3),...
                TEllipsoidFactory.createInstance('hyperplane', [1, 1, 2]', 2),...
                hpObj.fromRepMat(1, 1, [5 5 5]),...
                hpObj.fromRepMat(1, 1, [5 5 5])};
            objArrCVec{7}(1) = TEllipsoidFactory.createInstance('hyperplane');
        end
        
        function SArrCVec = getToStructStruct()
            absTol=elltool.conf.Properties.getAbsTol();
            relTol=elltool.conf.Properties.getRelTol();
            %
            SArrCVec = {struct('normal', [1, 1, 2]', 'shift', 3),...
                struct('normal', [], 'shift', []),...
                struct('normal', [], 'shift', []),...
                struct('normal', [1, 1, 2]', 'shift',...
                3, 'absTol', absTol, 'relTol',relTol),...
                struct('normal', [1, 1, 2]', 'shift', ...
                3, 'absTol',absTol),...
                struct('normal', num2cell(ones(5, 5, 5)), ...
                'shift', num2cell(ones(5, 5, 5))),...
                struct('normal', num2cell(ones(5, 5, 5)), ...
                'shift', num2cell(ones(5, 5, 5)))};
            SArrCVec{1} = normalize(SArrCVec{1});
            SArrCVec{4} = normalize(SArrCVec{4});
            SArrCVec{5} = normalize(SArrCVec{5});
            
            function SHpNormalized = normalize(SHp)
                SHpNormalized = SHp;
                SHpNormalized.shift = ...
                    SHpNormalized.shift/norm(SHpNormalized.normal);
                SHpNormalized.normal =...
                    SHpNormalized.normal/norm(SHpNormalized.normal);
            end
        end
        
        function isPropsCVec = getToStructIsPropIncluded()
            isPropsCVec = {false, false, false, true,...
                false, false, false};
        end
        
        function isResultCVec = getToStructResult()
            isResultCVec = {true, true, false, true, false, true, false};
        end
        
        function testNumber = getToStructTestNumber()
            testNumber = 7;
        end
        
        function objArrCVec = getFromStructObj()
            import elltool.core.test.mlunit.TEllipsoidFactory;
            hpObj = TEllipsoidFactory.createInstance('hyperplane');
            objArrCVec = {TEllipsoidFactory.createInstance('hyperplane', [1, 2]', 3),...
                TEllipsoidFactory.createInstance('hyperplane', [1, 2]', 3),...
                TEllipsoidFactory.createInstance('hyperplane'),...
                TEllipsoidFactory.createInstance('hyperplane', [1, 2]', 3),...
                hpObj.fromRepMat(1, 1, [5 5 5]),...
                hpObj.fromRepMat(1, 1, [5 5 5])};
            objArrCVec{6}(1) = TEllipsoidFactory.createInstance('hyperplane');
        end
        
        function SArrCVec = getFromStructStruct()
            absTol=elltool.conf.Properties.getAbsTol();
            %
            SArrCVec = {struct('normal', [1, 2]', 'shift', 3),...
                struct('normal', [1, 2]', 'shift', 3),...
                struct('normal', [1, 2]', 'shift', 3,...
                'absTol', absTol*10),...
                struct('normal', [1, 2]', 'shift', 3,...
                'absTol', absTol*10),...
                struct('normal', num2cell(ones(5, 5, 5)), ...
                'shift', num2cell(ones(5, 5, 5))),...
                struct('normal', num2cell(ones(5, 5, 5)), ...
                'shift', num2cell(ones(5, 5, 5)))};
        end
        
        function isResultCVec = getFromStructResult()
            isResultCVec = {true, true, false, false, true, false};
        end
        
        function testNumber = getFromStructTestNumber()
            testNumber = 6;
        end
        
        function objArrCVec = getDisplayObj()
            import elltool.core.test.mlunit.TEllipsoidFactory;
            hpObj = TEllipsoidFactory.createInstance('hyperplane');
            objArrCVec = {TEllipsoidFactory.createInstance('hyperplane', [1, 2]', 3),...
                TEllipsoidFactory.createInstance('hyperplane'),...
                TEllipsoidFactory.createInstance('hyperplane', [1, 1]', 3),...
                hpObj.fromStruct(struct('normal',...
                num2cell(ones(5, 5, 5)), ...
                'shift', num2cell(ones(5, 5, 5)))),...
                TEllipsoidFactory.createInstance('hyperplane', [1, 2]', 3), ...
                TEllipsoidFactory.createInstance(...
                'ellipsoid')};
            objArrCVec{5} = [objArrCVec{5} objArrCVec{5}];
        end
        
        function stringsCVec = getDisplayStrings()
            stringsCVec = {'hyperplane object', ...
                'Properties',...
                'shift',...
                'normal',...
                'Hyperplane shift'};
            stringsCVec = repmat({stringsCVec}, 1, 6);
            stringsCVec{5} = horzcat(stringsCVec{5}, 'objArr(1, 1)');
        end
        
        function isResultCVec = getDisplayResult()
            isResultCVec = {true, true, true, true, true, false};
        end
        
        function testNumber = getDisplayTestNumber()
            testNumber = 6;
        end
        
        function objArrCVec = getEqFstObj()
            import elltool.core.test.mlunit.TEllipsoidFactory;
            hpObj = TEllipsoidFactory.createInstance('hyperplane');
            objArrCVec = {TEllipsoidFactory.createInstance('hyperplane', [1, 2]', 3),...
                TEllipsoidFactory.createInstance('hyperplane'),...
                TEllipsoidFactory.createInstance('hyperplane', [1, 1]', 3),...
                TEllipsoidFactory.createInstance('hyperplane', [1, 2]', 3),...
                TEllipsoidFactory.createInstance('hyperplane', [1, 2]', 3),...
                hpObj.fromStruct(struct('normal',...
                num2cell(ones(5, 5, 5)), ...
                'shift', num2cell(ones(5, 5, 5)))),...
                hpObj.fromStruct(struct('normal',...
                num2cell(ones(5, 5, 5)), ...
                'shift', num2cell(ones(5, 5, 5)))),...
                TEllipsoidFactory.createInstance('hyperplane', [1, 2]', 3)};
            objArrCVec{8} = [objArrCVec{8} objArrCVec{8}];
        end
        
        function objArrCVec = getEqSndObj()
            import elltool.core.test.mlunit.TEllipsoidFactory;
            hpObj = TEllipsoidFactory.createInstance('hyperplane');
            objArrCVec = {TEllipsoidFactory.createInstance('hyperplane', [1, 2]', 3),...
                TEllipsoidFactory.createInstance('hyperplane'),...
                TEllipsoidFactory.createInstance('hyperplane', [1, 1]', 3),...
                TEllipsoidFactory.createInstance('hyperplane', [1, 1]', 3),...
                TEllipsoidFactory.createInstance('hyperplane'),...
                hpObj.fromStruct(struct('normal',...
                num2cell(ones(5, 5, 5)), ...
                'shift', num2cell(ones(5, 5, 5)))),...
                hpObj.fromStruct(struct('normal',...
                num2cell(ones(5, 5, 5)), ...
                'shift', num2cell(ones(5, 5, 5)))),...
                TEllipsoidFactory.createInstance('hyperplane', [1, 2]', 3)};
            objArrCVec{7}(1) = TEllipsoidFactory.createInstance('hyperplane');
            objArrCVec{8} = [objArrCVec{8} objArrCVec{8}];
        end
        
        function isResultCVec = getEqResult()
            isResultCVec = {true, true, true, false, false, true, false, true};
        end
        
        function testNumber = getEqTestNumber()
            testNumber = 8;
        end
    end
    
    methods (Access = public)
        function self = HyperplaneDispStructTC(varargin)
            self = self@elltool.core.test.mlunit.ADispStructTC(varargin{:});
        end
    end
end