classdef ReachContLTIProblemDef<...
        gras.ellapx.lreachuncert.LReachContProblemDef
    methods (Static,Access=protected)
        % check whether there are no 't' occurences
        function isOk=isConst(mCMat)
            isOk=all(reshape(cellfun('isempty',strfind(mCMat,'t')),[],1));
        end
    end
    methods
        function self=ReachContLTIProblemDef(aCMat,bCMat,...
                pCMat,pCVec,cCMat,qCMat,qCVec,x0Mat,x0Vec,tLims)
            %
            import gras.ellapx.lreachuncert.ReachContLTIProblemDef;
            %
            if ~(ReachContLTIProblemDef.isConst(aCMat)&&...
                    ReachContLTIProblemDef.isConst(bCMat)&&...
                    ReachContLTIProblemDef.isConst(pCMat)&&...
                    ReachContLTIProblemDef.isConst(pCVec)&&...
                    ReachContLTIProblemDef.isConst(cCMat)&&...
                    ReachContLTIProblemDef.isConst(qCMat)&&...
                    ReachContLTIProblemDef.isConst(qCVec))
                modgen.common.throwerror('wrongInput',...
                    'Input depends on ''t''');
            end
            %
            self=self@gras.ellapx.lreachuncert.LReachContProblemDef(...
                aCMat,bCMat,pCMat,pCVec,cCMat,qCMat,qCVec,x0Mat,x0Vec,...
                tLims);
        end
    end
end