function [isParTbxInstalled,isAltPartTbxInstalled]=...
    isparttbxinst()
isParTbxInstalled=~isempty(which('getCurrentTask'));
isAltPartTbxInstalled=...
    ~isempty(which('modgen.pcalcalt.auxdfeval'));