classdef RegProblemDynamicsFactory
    methods (Static)
        function outDynObj =...
                create(pDynObj, isRegEnabled, isJustCheck, regTol)
            import modgen.common.throwerror;
            if isRegEnabled
                if isa(pDynObj,...
                        'gras.ellapx.lreachuncert.probdyn.IReachProblemDynamics')
                    outDynObj =...
                        gras.ellapx.lreachuncert.probdyn.RegProblemDynamics(...
                        pDynObj, isJustCheck, regTol);
                elseif isa(pDynObj,...
                        'gras.ellapx.lreachplain.probdyn.IReachProblemDynamics')
                    outDynObj =...
                        gras.ellapx.lreachplain.probdyn.RegProblemDynamics(...
                        pDynObj, isJustCheck, regTol);
                else
                    throwerror('wrongInput',...
                        ['input object must be either ',...
                        'lreachplain.probdyn.IReachProblemDynamics or ',...
                        'lreachuncert.probdyn.IReachProblemDynamics']);
                end
            else
                outDynObj = pDynObj;
            end
        end
    end
end