function results=run_tests(varargin)
logger=modgen.logging.log4j.Log4jConfigurator.getLogger();
%
resList{2}=lib_run_tests(varargin{:});
resList{1}=mlunitext.runtestcase(...
'elltool.linsys.test.mlunit.LinSysTestCase');
results=[resList{:}];
%
[errorCount,failCount]=results.getErrorFailCount();
logger.info(sprintf([...
    '\n\n+--------------------------------------------+',...
    '\n|      ELLIPSOID TOOLBOX TEST RESULTS        |',...
    '\n|         (FAILURES: %d, ERRORS %d)            |',...
    '\n+--------------------------------------------+'],....
    failCount,errorCount));