function results=run_tests(varargin)
logger=modgen.logging.log4j.Log4jConfigurator.getLogger();
results=lib_run_tests(varargin{:});
%
[errorCount,failCount]=mlunitext.countfailsinresults(results);
logger.info(sprintf([...
    '\n\n+--------------------------------------------+',...
    '\n|      ELLIPSOID TOOLBOX TEST RESULTS        |',...
    '\n|         (FAILURES: %d, ERRORS %d)            |',...
    '\n+--------------------------------------------+'],....
    failCount,errorCount));