classdef EllApxCollectionBuilder<gras.ellapx.gen.EllApxCollectionBuilder
    methods      
        function self=EllApxCollectionBuilder(varargin)
            self=self@gras.ellapx.gen.EllApxCollectionBuilder(varargin{:});
        end
        %
        function ellTubeRel=getEllTubes(self)
            import gras.ellapx.uncertcalc.log.Log4jConfigurator;
            logger=Log4jConfigurator.getLogger();
            ellTubeRel=gras.ellapx.smartdb.rels.EllTubeNotTight();
            nBuilders=length(self.builderList);
            for iBuilder=1:nBuilders
                tStart=tic;
                ellTubeTempRel=self.builderList{iBuilder}.getEllTubes();
                ellTubeRel.unionWith(ellTubeTempRel);
                schemaNamesStr=...
                    ['{',modgen.string.catwithsep(...
                    unique(ellTubeTempRel.approxSchemaName),','),'}'];
                apxTypeStr=['{',modgen.string.catwithsep(...
                    arrayfun(@char,unique(ellTubeTempRel.approxType),...
                    'UniformOutput',false),','),'}'];
                logger.info(...
                    sprintf(['building approximation with ',...
                    'types=%s, schema=%s, #tubes=%d, calc. ',...
                    'precision=%d: done, time elapsed =%s sec.'],...
                    schemaNamesStr,apxTypeStr,...
                    ellTubeTempRel.getNTuples(),...
                    self.builderList{iBuilder}.getCalcPrecision(),...
                    num2str(toc(tStart))));
            end
        end
    end
end
