classdef ABasicEllipsoid < handle
    properties(Access=protected) 
        absTol
        relTol 
    end
    %
    methods(Abstract)
        [propArr,propVal]=getProperty(ellArr,propName,fPropFun)
        [dimArr,rankArr]=dimension(myEllArr)
    end
    methods(Access=protected)
        checkIfScalar(self,errMsg)
        [isEqualArr,reportStr]=isEqualInternal(ellFirstArr,...
            ellSecArr,isPropIncluded)
    end
    methods(Access=protected,Static)
        [propArr,propVal]=getPropertyInternal(propName,fPropFun)
    end
    methods(Static)
        ellArr=fromRepMatInternal(ellObj,sizeVec)
        checkIsMeInternal(objType,ellArr,varargin)
    end
    methods(Access=protected,Abstract)
        checkIsMeVirtual(ellArr,varargin)
        copyEllObj=getSingleCopy(ellObj)
        ellObj=ellFactory(self)
    end
    methods 
        [absTolArr,absTolVal]=getAbsTol(ellArr,varargin)
        [relTolArr,relTolVal]=getRelTol(ellArr,varargin)
        copyEllArr=getCopy(ellArr)
        isPositiveArr=isEmpty(myEllArr)
    end
end