% An example of creating nTubes ellipsoid tube objects using fromQArrays
% function with the same type of approximation.
[nTubes, nPoints, nDims, absTol, relTol, timeVec,...
    sTime, lsGoodDirVec, ltGoodDirArray, aMat, qArrayList] = ...
    gras.ellapx.smartdb.test.examples.getData();
[approxSchemaDescr, approxSchemaName, approxType] = ...
    gras.ellapx.smartdb.test.examples.getSameApprox();
fromMatEllTubeObj=gras.ellapx.smartdb.rels.EllTube.fromQArrays(...
    qArrayList, aMat, timeVec,...
    ltGoodDirArray, sTime, approxType, approxSchemaName,...
    approxSchemaDescr, absTol, relTol);