repoPath=rmlastnpathparts(fileparts(which(mfilename)),1);
deploymentPath=[repoPath,filesep,'install'];
%
rootPathList{1}=repoPath;
pathPatternToExclude='\.git';
pathList=genpathexclusive(rootPathList,pathPatternToExclude);
restoredefaultpath;
addpath(pathList{:});
savepath([deploymentPath,filesep,'pathdef.m']);