function SInput = patch_010_rename_scale_factors(~,SInput)
SInput.ellipsoidalApxProps.internalApx.dispScaleFactor=...
    SInput.ellipsoidalApxProps.internalApx.scaleFactor;
SInput.ellipsoidalApxProps.internalApx=rmfield(...
    SInput.ellipsoidalApxProps.internalApx,'scaleFactor');
%
SInput.ellipsoidalApxProps.externalApx.dispScaleFactor=...
    SInput.ellipsoidalApxProps.externalApx.scaleFactor;
SInput.ellipsoidalApxProps.externalApx=rmfield(...
    SInput.ellipsoidalApxProps.externalApx,'scaleFactor');