
 t = 0.886;
 ctObj = rsObj.cut(t);
 bctObj = brsObj.cut(t);
 efEllMat = ctObj.get_ea();
 ebEllMat = bctObj.get_ea();
 fgcCVec = ctObj.get_goodcurves(); 
 fgcVec = fgcCVec{1};
%  dst = ebEllMat.distance(fgcVec);
%  fgcId = find(dst == max(dst));
 bgcCVec = bct.get_goodcurves(); 
%  bgcVec = bgcCVec{fgcId};
 bgcVec = bgcCVec{1};
 fCenter = ctObj.get_center();
 bCenter = bctObj.get_center();
 bgcVec = -(bgcVec - bCenter) + bCenter;
 ctObj.plotByEa(); hold on;
 bctObj.plotByEa('g'); hold on;
 ell_plot(fgcVec,'r*');
 ell_plot(bgcVec,'k*');
