 function  [ellTubeRelList]=fCalcTube2 (self, selfRelTol, ...
                newTimeVec,  approxType, atStrCMat,...
                btStrCMat, ptStrCMat, ptStrCVec, ctStrCMat, ...
                qtStrCMat, qtStrCVec, x0MatArray, ...
                x0VecMat,l0Mat,isDisturbance)
            
            probDynObj = self.getProbDynamics(atStrCMat, ...
                    btStrCMat, ptStrCMat, ptStrCVec, ctStrCMat, ...  
                    qtStrCMat, qtStrCVec, x0MatArray, ...
                    x0VecMat, newTimeVec, selfRelTol, ...
                    isDisturbance);
                %ellTubeRelVec{il0Num} = self.makeEllTubeRel(...
                ellTubeRelVec = self.makeEllTubeRel(...
                    probDynObj, l0Mat, ...
                    newTimeVec, isDisturbance, selfRelTol, approxType);
                %ellTubeRelList{il0Num} = ...
                ellTubeRelList = ...
                    ellTubeRelVec.getTuplesFilteredBy(...
                    APPROX_TYPE, approxType).getData();
                     %ellTubeRelVec{il0Num}.getTuplesFilteredBy(...
 
 
 end