 function  [reachSetObj]=fCalcTube3 (reachSetObj,outReachObjSwitchSysTimeVec,...
      outReachObjIsBackward, outReachObjLinSysCVecILinSys)
  
     reachSetObj = ...
                    reachSetObj.evolve(...
                    getNewTime(outReachObjSwitchSysTimeVec,...  
                    outReachObjIsBackward,iLinSys),...
                    outReachObjLinSysCVecILinSys);
  
 end
