function result=run_tests(varargin)
suite = mlunitext.test_suite.fromTestCaseNameList({
    'elltool.core.test.mlunit.PolarIllCondTC',...
    'elltool.core.test.mlunit.EllipsoidIntUnionTC',...
    'elltool.core.test.mlunit.EllipsoidTestCase',...
    'elltool.core.test.mlunit.EllipsoidSecTestCase',...
    'elltool.core.test.mlunit.HyperplaneTestCase',...
    'elltool.core.test.mlunit.GenEllipsoidPlotTestCase',...
    'elltool.core.test.mlunit.GenEllipsoidSecTC',...
    'elltool.core.test.mlunit.GenEllipsoidTestCase',...
    'elltool.core.test.mlunit.ElliIntUnionTCMultiDim',...
    'elltool.core.test.mlunit.EllTCMultiDim',...
    'elltool.core.test.mlunit.EllSecTCMultiDim',...
    'elltool.core.test.mlunit.MPTIntegrationTestCase',...
    'elltool.core.test.mlunit.EllipsoidPlotTestCase',...
    'elltool.core.test.mlunit.EllAuxTestCase',...
    'elltool.core.test.mlunit.HyperplanePlotTestCase',...
    'elltool.core.test.mlunit.EllipsoidMinkPlotTestCase',...
    'elltool.core.test.mlunit.EllipsoidBasicSecondTC',...
    'elltool.core.test.mlunit.EllipsoidDispStructTC',...
    'elltool.core.test.mlunit.HyperplaneDispStructTC'
    }, varargin);
%
suite1Obj=mlunitext.test_suite.fromTestCaseNameList(...
    'elltool.core.test.mlunit.PrameterizedTC',...
    {@ellipsoid,'marker','Ellipsoid'});
%
suite2Obj=mlunitext.test_suite.fromTestCaseNameList(...
    'elltool.core.test.mlunit.PrameterizedTC',...
    {@elltool.core.GenEllipsoid,'marker','GenEllipsoid'});
%
suite3Obj=mlunitext.test_suite.fromTestCaseNameList(...
    'elltool.core.test.mlunit.PrameterizedTC',...
    {@hyp,'marker','Hyperplane'});

suiteObj=mlunitext.test_suite.fromSuites(suite,suite1Obj,...
    suite2Obj,suite3Obj);

result=runner.run(suiteObj);
    function res = hyp(x,y,varargin)
        res = hyperplane(x,y(1),varargin{:});
    end
end