function result=run_GenEllipsoid_tests(varargin)
import elltool.core.test.EllFactory;

runner = mlunitext.text_test_runner(1, 1);
loader = mlunitext.test_loader;

suiteList = {};
%Tests for GenEllipsoid class;
%1
suiteList{end + 1} = loader.load_tests_from_test_case(...
    'elltool.core.test.mlunit.EllipsoidIntUnionTC', ...
    EllFactory('GenEllipsoid'));
%2
suiteList{end + 1} = loader.load_tests_from_test_case(...
    'elltool.core.test.mlunit.EllipsoidTestCase', ...
    EllFactory('GenEllipsoid'));
%3
suiteList{end + 1} = loader.load_tests_from_test_case(...
    'elltool.core.test.mlunit.EllipsoidSecTestCase', ...
    EllFactory('GenEllipsoid'));
%4
suiteList{end + 1} = loader.load_tests_from_test_case(...
    'elltool.core.test.mlunit.HyperplaneTestCase', ...
    EllFactory('GenEllipsoid'));
%5
suiteList{end + 1} = loader.load_tests_from_test_case(...
    'elltool.core.test.mlunit.ElliIntUnionTCMultiDim', ...
    EllFactory('GenEllipsoid'));
%6
suiteList{end + 1} = loader.load_tests_from_test_case(...
    'elltool.core.test.mlunit.EllTCMultiDim', ...
    EllFactory('GenEllipsoid'));
%7
suiteList{end + 1} = loader.load_tests_from_test_case(...
    'elltool.core.test.mlunit.EllSecTCMultiDim', ...
    EllFactory('GenEllipsoid'));
%8
suiteList{end + 1} = loader.load_tests_from_test_case(...
    'elltool.core.test.mlunit.MPTIntegrationTestCase', ...
    EllFactory('GenEllipsoid'));
%9
suiteList{end + 1} = loader.load_tests_from_test_case(...
    'elltool.core.test.mlunit.EllipsoidPlotTestCase', ...
    EllFactory('GenEllipsoid'));
%10
suiteList{end + 1} = loader.load_tests_from_test_case(...
    'elltool.core.test.mlunit.EllAuxTestCase', ...
    EllFactory('GenEllipsoid'));
%11
suiteList{end + 1} = loader.load_tests_from_test_case(...
    'elltool.core.test.mlunit.HyperplanePlotTestCase', ...
    EllFactory('GenEllipsoid'));
%12
suiteList{end + 1} = loader.load_tests_from_test_case(...
    'elltool.core.test.mlunit.EllipsoidMinkPlotTestCase', ...
    EllFactory('GenEllipsoid'));
%13
suiteList{end + 1} = loader.load_tests_from_test_case(...
    'elltool.core.test.mlunit.EllipsoidBasicSecondTC', ...
    EllFactory('GenEllipsoid'));
%14
suiteList{end + 1} = loader.load_tests_from_test_case(...
    'elltool.core.test.mlunit.EllipsoidDispStructTC', ...
    EllFactory('GenEllipsoid'));
%15
suiteList{end + 1} = loader.load_tests_from_test_case(...
    'elltool.core.test.mlunit.HyperplaneDispStructTC', ...
    EllFactory('GenEllipsoid'));
%16
suiteList{end + 1} = loader.load_tests_from_test_case(...
    'elltool.core.test.mlunit.GenEllipsoidPlotTestCase', ...
    EllFactory('GenEllipsoid'));
%17
suiteList{end + 1} = loader.load_tests_from_test_case(...
    'elltool.core.test.mlunit.GenEllipsoidTestCase', ...
    EllFactory('GenEllipsoid'));


testLists = cellfun(@(x)x.tests,suiteList,'UniformOutput',false);
testList=horzcat(testLists{:});
suite = mlunitext.test_suite(testList);
suite=suite.getCopyFiltered(varargin{:});
result=runner.run(suite);
