function resultObj=run_param_test(varargin)
    suite1Obj=mlunitext.test_suite.fromTestCaseNameList(...
        'elltool.core.test.mlunit.PrameterizedTC',...
        {@ellipsoid,'marker','Ellipsoid'});
    %
    suite2Obj=mlunitext.test_suite.fromTestCaseNameList(...
        'elltool.core.test.mlunit.PrameterizedTC',...
        {@elltool.core.GenEllipsoid,'marker','GenEllipsoid'});
    %
    suite3Obj=mlunitext.test_suite.fromTestCaseNameList(...
        'elltool.core.test.mlunit.PrameterizedTC',...
        {@hyp,'marker','Hyperplane'});
            
    suiteObj=mlunitext.test_suite.fromSuites(suite1Obj,...
        suite2Obj,suite3Obj);
    runnerObj=mlunitext.text_test_runner(1,1);
    resultObj=runnerObj.run(suiteObj);
    
    function res = hyp(x,y,varargin)
        res = hyperplane(x,y(1),varargin{:});
    end
end
