function isPositive=iscellofstrorfunc(inpArray)
isPositive=all(cellfun('isclass',inpArray,'function_handle')|...
    (cellfun('ndims',inpArray)==2&cellfun('size',inpArray,1)==1&...
    cellfun('isclass',inpArray,'char')));